const districtsOfZone = {
    mechi:[
        'Ilam',
        'Jhapa',
        'Panchthar',
        'Taplejung'
    ],
    koshi:[
        'Sankhuwasbha',
        'Bhojpur',
        'Terthum',
        'Dhankuta',
        'Morang',
        'Sunsari'
    ],
    sagarmatha:[
        'Soukhumbu',
        'Khotang', 
        'Okhaldhunga',
        'Udayapur',
        'Siraha',
        'Saptri'
    ],
    janakpur:[
        'Dolakha',
        'Ramechap', 
        'Sindhuli', 
        'Dhanusha',    
        'Sarlahi',
        'Mahottri' 
    ],
    bagmati:[
        'Dhading',
        'Rasuwa', 
        'Sindhupalchok', 
        'Kavrepalchok', 
        'Nuwakot',
        'Lalitpur',
        'Bhaktapur',
        'Kathamandu' 
    ],
    narayani:[
        'Makwanpur',
        'Chitawan',
        'Parsa', 
        'Bara' 
    ],
    gandaki:[
        'Manang', 
        'Gorkha',
        'Kaski', 
        'Lamjung',
        'Shyangja', 
        'Tanahun'    
    ],
    lumbini:[
        'Gulmi', 
        'Arghakhanchi', 
        'Kapilbastu', 
        'Palpa', 
        'Rupandehi', 
        'Nawalparasi' 
    ],
    dhaulagiri:[
        'Mustang',
        'Myagdi',
        'Baglung',
        'Parbat'
    ],
    rapti:[
        'Rukum', 
        'Salyan',
        'Rolpa', 
        'Pyuthan', 
        'Dang' 
    ],
    karnali:[
        'Humla', 
        'Dolpa',
        'Mugu', 
        'Kalikot',
        'Jumla' 
    ],
    bheri:[
        'Dailekh', 
        'Surkhet',
        'Jajarkot',
        'Bardiya', 
        'Banke'
    ],
    seti:[
        'Bajhang', 
        'Bajura',
        'Doti', 
        'Achham' ,
        'Kailali'
    ],
    mahakali:[
        'Darchula',
        'Baitadi', 
        'Dadeldhura',
        'Kanchanpur'
    ]
}

module.exports = districtsOfZone;
