const localBodies = {
  Achham: [
    "Bannigadi Jayagad Rural Municipality",
    "Chaurpati Rural Municipality",
    "Dhakari Rural Municipality",
    "Kamalbazar Municipality",
    "Mangalsen Municipality",
    "Mellekh Rural Municipality",
    "Panchadeval Binayak Municipality",
    "Ramaroshan Rural Municipality",
    "Sanphebagar Municipality",
    "Turmakhand Rural Municipality"
  ],
  Arghakhanchi: [
    "Sandhikharka Municipality",
    "Sitganga Municipality",
    "Bhumikasthan Municipality",
    "Chhatradev Rural Municipality",
    "Paadini Rural Municipality",
    "Malarani Rural Municipality"
  ],
  Baglung: [
    "Baglung Municipality",
    "Galkot Municipality",
    "Jaimini Rural Municipality",
    "Dhorpatan Rural Municipality",
    "Bareng Rural Municipality",
    "Kathekhola Rural Municipality",
    "Taman Khola Rural Municipality",
    "Tarakhola Rural Municipality",
    "Nishikhola Rural Municipality",
    "Badigaadh Rural Municipality"
  ],
  Baitadi: [
    "Dasharath Chand Municipality",
    "Patan Municipality",
    "Melauni Municipality",
    "Purchaudi Municipality",
    "Surnaya Rural Municipality",
    "Sigash Rural Municipality",
    "Shivanath Rural Municipality",
    "Pancheshwor Rural Municipality",
    "Dogada Kedar Rural Municipality",
    "Dilasaini Rural Municipality"
  ],
  Bajhang: [
    "Jayaprithivi Municipality",
    "Bungal Municipality",
    "Talkot Rural Municipality",
    "Masta Rural Municipality",
    "Khaptad Channa Rural Municipality",
    "Thalara Rural Municipality",
    "Bitthadachir Minicipality",
    "Surma Rural Municipality",
    "Chabbish Pathivara Rural Municipality",
    "Durgathali Rural Municipality",
    "Kedarsyuu Rural Municipality",
    "Kaada Rural Municipality"
  ],
  Bajura: [
    "Badimalika Municipality",
    "Triveni Municipality",
    "Budiganga Municipality",
    "Budinanda Municipality",
    "Gaumul Rural Municipality",
    "Pandavgufa Rural Municipality",
    "Swami Kartik Rural Municipality",
    "Chededaha Rural Municipality",
    "Himali Rural Municipality"
  ],
  Banke: [
    "Nepalgunj Sub Metropolitan City",
    "Kohalpur Municipality",
    "Narainapur Rural Municipality",
    "Rapti Sonari Rural Municipality",
    "Bajainath Rural Municipality",
    "Khajura Rural Municipality",
    "Daduwa Rural Municipality",
    "Janaki Rural Municipality"
  ],
  Bara: [
    "Kalaiya Sub-Metropolitan City",
    "Jitpur-Simara Sub-Metropolitan City",
    "Kolhawi Municipality",
    "Nijgadh Municipality",
    "Mahagadimai Municipality",
    "Simraungadh Municipality",
    "Pachraita Municipality",
    "Aadarshkotwal Rural Municipality",
    "Karaiyamai Rural Municipality",
    "Devtal Rural Municipality",
    "Parwanipur Rural Municipality",
    "Prasauni Rural Municipality",
    "Fota Rural Municipality",
    "Baragadhi Rural Municipality",
    "Suwarna Rural Municipality",
    "Bishrampur Rural Municipality"
  ],
  Bardiya: [
    "Gulariya Municipality",
    "Madhuwan Municipality",
    "Rajapur Municipality",
    "Thakurbaba Municipality",
    "Baashgadhi Municipality",
    "Bharabardiya Municipality",
    "Badaiya Tal Rural Municipality",
    "Gorewa Rural Municipality"
  ],
  Bhaktapur: [
    "Bhaktapur Municipality",
    "Changunarayan Municipality",
    "Madhyapur Thimi Municipality",
    "Suryabinayak Municipality"
  ],
  Bhojpur: [
    "Bhojpur Municipality",
    "Sadananda Municipality",
    "Tyamke-Maiyum ",
    "Ramprasad Rai Rural Municipality",
    "Arun Rural Municipality",
    "Pauwadhungma Rural Municipality",
    "Salpasillicho Rural Municipality",
    "Aamchwok Rural Municipality",
    "Hatuwagadhi Rural Municipality"
  ],
  Chitwan: [
    "Bharatpur Metropolitan City",
    "Ichchhakamana Rural Municipality",
    "Kalika Municipality",
    "Khairahani Municipality",
    "Madi Municipality",
    "Rapti Municipality",
    "Ratnanagar Municipality"
  ],
  Dadeldhura: [
    "Aalital Rural Municipality",
    "Ajayameru Rural Municipality",
    "Amargadhi Municipality",
    "Bhageshwor Rural Municipality",
    "Ganyapadhura Rural Municipality",
    "Navadurga Rural Municipality",
    "Parshuram Municipality"
  ],
  Dailekh: [
    "Aathbis Municipality",
    "Bhagawatimai Rural Municipality",
    "Bhairabi Rural Municipality",
    "Chamunda Bindrasaini Municipality",
    "Dullu Municipality",
    "Dungeshwar Rural Municipality",
    "Gurans Rural Municipality",
    "Mahabu Rural Municipality",
    "Narayan Municipality",
    "Naumule Rural Municipality",
    "Thantikandh Rural Municipality"
  ],
  Dang: [
    "Tulsipur Sub Metropolitan City",
    "Ghorahi Sub Metropolitan City",
    "Lamahi Metropolitan City",
    "Bangala CHuli Rural Municipality",
    "Dangisharan Rural Municipality",
    "Gadwa Rural Municipality",
    "Rajpur Rural Municipality",
    "Rapti Rural Municipality",
    "Shantinagar Rural Municipality",
    "Babai Rural Municipality"
  ],
  Darchula: [
    "Mahakali Municipality",
    "Sailyashikhar Municipality",
    "Malirjun Rural Municipality",
    "Api Himal Rural Municipality",
    "Duhuu Rural Municipality",
    "Naugadh Rural Municipality",
    "Marma Rural Municipality",
    "Lekam Rural Municipality",
    "Byash Rural Municipality"
  ],
  Dhading: [
    "Dhunibesi Municipality",
    "Nilkhantha Municipality",
    "Khaniyabash Rural Municipality",
    "Gajuri Rural Municipality",
    "Galchi Rural Municipality",
    "Gangajamuna Rural Municipality",
    "Jwalamukhi Rural Municipality",
    "Tharke Rural Municipality",
    "Netrawati Rural Municipality",
    "Benighat-Rorang Rural Municipality",
    "Ruby Valley Rural Municipality",
    "Siddha Khola Rural Municipality",
    "Tripura Sundari Rural Municipality"
  ],
  Dhankuta: [
    "Pakhribash Municipality",
    "Dhankuta Municipality",
    "Mahalakshmi Municipality",
    "Sangurigadhigadhi Rural Municipality",
    "Khalsha Chhintang Sahidbhumi Rural Municipality",
    "Chathar Jorpati Rural Municipality",
    "Chaubise Rural Municipality"
  ],
  Dhanusa: [
    "Janakpur Sub-Metropolitan City",
    "Chireshwornath Municipality",
    "Ganeshman-Charnath Municipality",
    "Dhanushadham Municipality",
    "Nagarain Municipality",
    "Bideha Municipality",
    "Mithila Municipality",
    "Mithila Birahi Municipality",
    "Sahidnagar Municipality",
    "Sawaila Municipality",
    "Kamala Municipality",
    "Hanshapur Municipality",
    "Aurahi Municipality",
    "Janak Nandini Rural Municipality",
    "Bateshwor Rural Municipality",
    "Mukhiyapatti Musaharmiya Rural Municipality",
    "Lashminiya Rural Municipality",
    "Dhanauji Rural Municipality"
  ],
  Dolakha: [
    "Baiteshwor Rural Municipality",
    "Bhimeswor Municipality",
    "Bigu Rural Municipality",
    "Gaurishankar Rural Municipality",
    "Jiri Municipality",
    "Kalinchok Rural Municipality",
    "Melung Rural Municipality",
    "Sailung Rural Municipality",
    "Tamakoshi Rural Municipality"
  ],
  Dolpa: [
    "Chharka Tangsong Rural Municipality",
    "Dolpo Buddha Rural Municipality",
    "Jagadulla Rural Municipality",
    "Kaike Rural Municipality",
    "Mudkechula Rural Municipality",
    "She Phoksundo Rural Municipality",
    "Thuli Bheri Municipality",
    "Tripurasundari Municipality"
  ],
  Doti: [
    "Dipayal Silgadh Municipality",
    "Shikhar Municipality",
    "Purvichauki Rural Municipality",
    "Badi Kedar Rural Municipality",
    "Jorayl Rural Municipality",
    "Sayal Rural Municipality",
    "Aadarsh Rural Municipality",
    "K.I.Singh Rural Municipality",
    "Bogatan Rural Municipality"
  ],
  EasternRukum: [
    "Bhume Rural Municipality",
    "Putha Uttarganga Rural Municipality",
    "Sisne Rural Municipality"
  ],
  Gorkha: [
    "Gorkha Municipality",
    "Palungtar Municipality",
    "Sulikot Rural Municipality",
    "Siranchwok Rural Municipality",
    "Ajirkot Rural Municipality",
    "Aarughat Rural Municipality",
    "Gandaki Rural Municipality",
    "Chumnumbri Rural Municipality",
    "Dharche Rural Municipality",
    "Bhimsne Rural Municipality",
    "Sahid Lakhan Rural Municipality",
  ],
  Gulmi: [
    "Musikot Municipality",
    "Resunga Municipality",
    "Ishma Municipality",
    "Kaligandaki Rural Municipality",
    "Gulmi Durbar Rural Municipality",
    "Satyawati Rural Municipality",
    "Chandrakot Rural Municipality",
    "Ruru Rural Municipality",
    "Chhatrakot Rural Municipality",
    "Dhurkot Rural Municipality",
    "Madane Rural Municipality",
    "Malika Rural Municipality"
  ],
  Humla: [
    "Adanchuli Rural Municipality",
    "Chankheli Rural Municipality",
    "Kharpunath Rural Municipality",
    "Namkha Rural Municipality",
    "Sarkegad Rural Municipality",
    "Simkot Rural Municipality",
    "Tajakot Rural Municipality"
  ],
  Ilam: [
    "Ilam Municipality",
    "Deumai Municipality",
    "Mai Municipality",
    "Suryodaya Municipality",
    "Fakfothum Rural Municipality",
    "Chulachuli Rural Municipality",
    "Mai Jogmai Rural Municipality",
    "Mangseung Rural Municipality",
    "Rong Rural Municipality",
    "Sandakpur Rural Municipality"
  ],
  Jajarkot: [
    "Barekot Rural Municipality",
    "Bheri Municipality",
    "Chhedagad Municipality",
    "Junichande Rural Municipality",
    "Kushe Rural Municipality",
    "Shivalaya Rural Municipality",
    "Tribeni Nalgad Municipality"
  ],
  Jhapa: [
    "Mechinagar Municipality",
    "Damak Municipality",
    "Kankai Municipality",
    "Bhadrapur Municipality",
    "Arjundhara Municipality",
    "Shivasatakshi Municipality",
    "Gauradaha Municipality",
    "Birtamod Municipality",
    "Kamal Rural Municipality",
    "Gaurigunj Rural Municipality",
    "Barhadashi Rural Municipality",
    "Jhapa Rural Municipality",
    "Buddhashanti Rural Municipality",
    "Hallibari Rural Municipality",
    "Kachankawal Rural Municipality"],
  Jumla: [
    "Chandannath Municipality",
    "Guthichaur Rural Municipality",
    "Hima Rural Municipality",
    "Kankasundari Rural Municipality",
    "Patarasi Rural Municipality",
    "Sinja Rural Municipality",
    "Tatopani Rural Municipality",
    "Tila Rural Municipality"
  ],
  Kailali: [
    "Dhangadi Sub Metropolitan City",
    "Tikapur Municipality",
    "Ghodaghodi Municipality",
    "Lamki Chuha Municipality",
    "Bhajani Municipality",
    "Godavari Municipality",
    "Gauriganga Municipality",
    "Janaki Rural Municipality",
    "Bargagoriya Rural Municipality",
    "Mohanyal Rural Municipality",
    "Kailari Rural Municipality",
    "Joshipur Rural Municipality",
    "Chure Rural Municipality"
  ],
  Kalikot: [
    "Khandachakra Municipality",
    "Mahawai Rural Municipality",
    "Narharinath Rural Municipality",
    "Pachaljharana Rural Municipality",
    "Palata Rural Municipality",
    "Raskot Municipality",
    "Sanni Triveni Rural Municipality",
    "Shubha Kalika Rural Municipality",
    "Tilagufa Municipality"
  ],
  Kanchanpur: [
    "Bhimdutta Municipality",
    "Punarwash Municipality",
    "Vedkot Municipality",
    "Mahakali Municipality",
    "Shuklaphata Municipality",
    "Belauri Municipality",
    "Krishnapur Municipality",
    "Baldaadi Rural Municipality",
    "Laljhadi Rural Municipality"
  ],
  Kapilvastu: [
    "Kapilvastu Municipality",
    "Buddhabhumi Municipality",
    "Shivaraj Municipality",
    "Maharajgunj Municipality",
    "Krishnanagar Municipality",
    "Baadranga Municipality",
    "Mayadevi Rural Municipality",
    "Yashodhara Rural Municipality",
    "Suddhodhan Rural Municipality",
    "Bijayanagar Rural Municipality"
  ],
  Kaski: [
    "Pokhara Lekhnath Metropolitan City",
    "Annapurna Rural Municipality",
    "Macchapucchre Rural Municipality",
    "Madi Rural Municipality",
    "Rupa Rural Municipality"
  ],
  Kathmandu: [
    "Kathmandu Metropolitan City",
    "Kageshwori-Manohara Municipality",
    "Kirtipur Municipality",
    "Gokarneshwor Municipality",
    "Chandragiri Municipality",
    "Tokha Municipality",
    "Tarakeshwor Municipality",
    "Dakshinkali Municipality",
    "Nagarjun Municipality",
    "Budhanilkantha Municipality",
    "Shankhapur Municipality"
  ],
  Kavrepalanchowk: [
    "Dhulikhel Municipality",
    "Banepa Municipality",
    "Panauti Municipality",
    "Panchkhal Municipality",
    "Namobuddha Municipality",
    "Mandandeupur Municipality",
    "Khanikhola Rural Municipality",
    "Chaurideurali Rural Municipality",
    "Temal Rural Municipality",
    "Bethanchwok Rural Municipality",
    "Vullu Rural Municipality",
    "Mahabharat Rural Municipality",
    "Roshi Rural Municipality",
  ],
  Khotang: [
    "Halesi-Tuwachung Municipality",
    "Rupakot-Majhuwagadhi Municipality",
    "Aishelukharka Rural Municipality",
    "Lamidanda Rural Municipality",
    "Jantedhunga Rural Municipality",
    "Khotehang Rural Municipality",
    "Kopilashgadhi Rural Municipality",
    "Diprung Rural Municipality",
    "Saakelaa Rural Municipality",
    "Brahapokhari Rural Municipality"
  ],
  Lalitpur: [
    "Lalitpur Metropolitan City",
    "Godavari Municipality",
    "Mahalakshmi Municipality",
    "Konjayoshom Rural Municipality",
    "Bagmati Rural Municipality",
    "Mahankal Rural Municipality"
  ],
  Lamjung: [
    "Besisahar Municipality",
    "Madhya Nepal Municipality",
    "Rainash Municipality",
    "Sundarbazar Rural Municipality",
    "Kwaholasothar Rural Municipality",
    "Dudhpokhari Rural Municipality",
    "Dodi Rural Municipality",
    "Marshyangdi Rural Municipality"
  ],
  Mahottari: [
    "Jaleshwor Municipality",
    "Bardibash Municipality",
    "Gaushala Municipality",
    "Loharpatti Municipality",
    "Ramgopalpur Municipality",
    "Manara Sishawa Municipality",
    "Matihani Municipality",
    "Bhagaha Municipality",
    "Balawa Municipality",
    "Aurahi Municipality",
    "Ekdara Rural Municipality",
    "Sonam Rural Municipality",
    "Samshi Rural Municipality",
    "Mahottari Rural Municipality",
    "Pipara Rural Municipality"
  ],
  Makwanpur: [
    "Hetauda Sub-Metropolitan City",
    "Thaha Municipality",
    "Inadra Sarowar Rural Municipality",
    "Bailash Rural Municipality",
    "Bakaiya Rural Municipality",
    "Bagmati Rural Municipality",
    "Bhimfedi Rural Municipality",
    "Makwanpur Gadhi Rural Municipality",
    "Manhari Rural Municipality",
    "Rakshirang Rural Municipality"
  ],
  Manang: [
    "Chame Rural Municipality",
    "Narfu Rural Municipality",
    "Nasong Rural Municipality",
    "Neshyang Rural Municipality"
  ],
  Morang: [
    "Biratnagar Metropolitan City",
    "Belwari Municipality",
    "Letang Municipality",
    "Pathari-Sanishchare Municipality",
    "Rangeli Municipality",
    "Ratuwamai Municipality",
    "Sunwarsa Municipality",
    "Urlabari Municipality",
    "Sundar Haraicha Municipality",
    "Budiganga Rural Municipality",
    "Dhanpalthan Rural Municipality",
    "Gramthan Rural Municipality",
    "Jahada Rural Municipality",
    "Kanepohari Rural Municipality",
    "Katahari Rural Municipality",
    "Kerabari Rural Municipality",
    "Miklajung Rural Municipality",
  ],
  Mugu: [
    "Chhayanath Rara Municipality",
    "Khatyad Rural Municipality",
    "Mugum Karmarong Rural Municipality",
    "Soru Rural Municipality"
  ],
  Mustang: [
    "Gharapjhong Rural Municipality",
    "Thasang Rural Municipality",
    "Dalome Rural Municipality",
    "Lhomanthang Rural Municipality",
    "Bharagau-Muktikshetra Rural Municipality"
  ],
  Myagdi: [
    "Beni Municipality",
    "Annapurna Rural Municipality",
    "Dhawalagiri Rural Municipality",
    "Mangala Rural Municipality",
    "Malika Rural Municipality",
    "Raghuganga Rural Municipality"
  ],
  Nawalpur: [
    "Binayi Tribeni Rural Municipality",
    "Bulingtar Rural Municipality",
    "Bungdikali Rural Municipality",
    "Devachuli Municipality",
    "Gaindakot Municipality",
    "Hupsekot Rural Municipality",
    "Kawasoti Municipality",
    "Madhyabindu Municipality"
  ],
  Nuwakot: [
    "Bidur Municipality",
    "Belkot Gadhi Municipality",
    "Kakani Rural Municipality",
    "Kispang Rural Municipality",
    "Tadi Rural Municipality",
    "Tarakeshwor Rural Municipality",
    "Gupeteshwor Rural Municipality",
    "Panchakanya Rural Municipality",
    "Likhu Rural Municipality",
    "Meghang Rural Municipality",
    "Shivapuri Rural Municipality",
    "Suryagadhi Rural Municipality"
  ],
  Okhaldhunga: [
    "Siddhicharan Municipality",
    "Khijidemba Rural Municipality",
    "Champadevi Rural Municipality",
    "Chisankhugadhi Rural Municipality",
    "Mane Bhanjyang Rural Municipality",
    "Molung Rural Municipality",
    "Likhu Rural Municipality",
    "Sunkoshi Rural Municipality"
  ],
  Palpa: [
    "Rampur Municipality",
    "Tansen Municipality",
    "Nishdi Rural Municipality",
    "Purwakhola Rural Municipality",
    "Rambha Rural Municipality",
    "Mathagadhi Rural Municipality",
    "Tinau Rural Municipality",
    "Bagnashkali Rural Municipality",
    "Ribdikot Rural Municipality",
    "Rainadevi Chahara Rural Municipality"
  ],
  Panchthar: [
    "Fidim Municipality",
    "Falelung Rural Municipality",
    "Falgunanda Rural Municipality",
    "Hilihang Rural Municipality",
    "Kummayak Rural Municipality",
    "Miklajung Rural Municipality",
    "Tumbewa Rural Municipality",
    "yangwarak Rural Municipality"
  ],
  Parasi: [
    "Bardghat Municipality",
    "Palhinand Rural Municipality",
    "Pratappur Rural Municipality",
    "Ramgram Municipality",
    "Sarawal Rural Municipality",
    "Sunwal Municipality",
    "Susta Rural Municipality"
  ],
  Parbat: [
    "Bihadi Rural Municipality",
    "Jaljala rural municipality",
    "Kusma Municipality",
    "Mahashila Rural Municipality",
    "Modi Rural Municipality",
    "Paiyun Rural Municipality",
    "Phalewas Municipality"
  ],
  Parsa: [
    "Birgunj Sub-Metropolitan City",
    "Pokhariya Municipality",
    "Parsha Gadhi Municipality",
    "Bahudarmai Municipality",
    "Jagarnathpur Rural Municipality",
    "Dhobini Rural Municipality",
    "Chipaharmai Rural Municipality",
    "Pakaha Mainapur Rural Municipality",
    "Bindabashini Rural Municipality",
    "Sakhuwa Prasaini Rural Municipality",
    "Praterwa Sugauli Rural Municipality",
    "Kalikamai Rural Municipality",
    "Thori Rural Municipality",
    "Jirabhawani Rural Municipality"
  ],
  Pyuthan: [
    "Pyuthan Municipality",
    "Sworgadwari Municipality",
    "Gaumukhi Rural Municipality",
    "Mandawi Rural Municipality",
    "Sarumarani Rural Municipality",
    "Mallarani Rural Municipality",
    "Nauwahini Rural Municipality",
    "Jhimruk Rural Municipality",
    "Eiyawati Rural Municipality"
  ],
  Ramechhap: [
    "Manthali Municipality",
    "Ramechhap Municipality",
    "Umakunda Rural Municipality",
    "Khandadevi Rural Municipality",
    "Gokulganga Rural Municipality",
    "Doramba Rural Municipality",
    "Likhu Rural Municipality",
    "Sunpati Rural Municipality",
  ],
  Rasuwa: [
    "Uttargaya Rural Municipality",
    "Kalika Rural Municipality",
    "Gosaikunda Rural Municipality",
    "Naukunda Rural Municipality",
    "Parwatikunda Rural Municipality"
  ],
  Rautahat: [
    "Chandrapur Municipality",
    "Garuda Municipality",
    "Gaur Municipality",
    "Baudhimai Municipality",
    "Brindrwan Municipality",
    "Devahi Gonahi Municipality",
    "Gadhimai Municipality",
    "Gajura Municipality",
    "Katahariya Municipality",
    "Madhav Narayan Municipality",
    "Fatuwa Narayan Municipality",
    "Ishnath Municipality",
    "Paroha Municipality",
    "Rajpur Municipality",
    "Rajdevi Municipality",
    "Maulapur Minicipality",
    "Durgabhawani Rural Municipality",
    "Yamunamai Rural Municipality"
  ],
  Rolpa: [
    "Ropla Municipality",
    "Triveni Rural Municipality",
    "Duikhola Rural Municipality",
    "Maadi Rural Municipality",
    "Runtigadhi Rural Municipality",
    "Lungri Rural Municipality",
    "Shuki Daha Rural Municipality",
    "Sunchahari Rural Municipality",
    "SurwadwatiRural Municipality",
    "Thawang Rural Municipality"
  ],
  Rupandehi: [
    "Butwal Sub-Metropolitan City",
    "Devdaha Municipality",
    "Lumbini Sanskritik Municiplaity",
    "Sainamaina Municipality",
    "Siddarthanagar Municipality",
    "Tilottama Municipality",
    "Gaidahawa Rural Municipality",
    "Kanchan Rural Municipality",
    "Kothiai Rural Municipality",
    "Marchawari Rural Municipality",
    "Mayadevi Rural Municipality",
    "Omsatiya Rural Municipality",
    "Rohini Rural Municipality",
    "Samarimai Rural Municipality",
    "Siyari Rural Municipality",
    "Siyari Rural Municipality",
    "Suddhodhan Rural Municipality"
  ],
  Salyan: [
    "Bagchaur Municipality",
    "Bangad Kupinde Municipality",
    "Chatreshwari Rural Municipality",
    "Darma Rural Municipality",
    "Dhorchaur Rural Municipality",
    "Kalimati Rural Municipality",
    "Kapurkot Rural Municipality",
    "Kumakhmalika Rural Municipality",
    "Shaarda Municipality",
    "Tribeni Rural Municipality"
  ],
  Sankhuwasabha: [
    "Chainpur Municipality",
    "Dharmadevi Municipality",
    "Khadwari Municipality",
    "Maadi Municipality",
    "Panchkhapan Municipality",
    "Bhotkhola Rural Municipality",
    "Chichila Rural Municipality",
    "Makalu Rural Municipality",
    "Sabhaa Pokhari Rural Municipality",
    "Silichong Rural Municipality"
  ],
  Saptari: [
    "Rajbiraj Municipality",
    "Kanchanrup Municipality",
    "Dakneshwori Municipality",
    "Bodewarsain Municipality",
    "Khadak Municipality",
    "Sambhunath Municipality",
    "Hanumannagar Kankalini Municipality",
    "Saptakoshi Municipality",
    "Agnisain Krishnasawaran Rural Municipality",
    "Chinnamasta Rural Municipality",
    "Mahadeva Rural Municipality",
    "Tirhut Rural Municipality",
    "Tilathi-Koiladi Rural Municipality",
    "Rupani Rural Municipality",
    "Belhi-Chapena Rural Municipality",
    "Bishnupur Rural Municipality",
    "Tirhut Rural Municipality"
  ],
  Sarlahi: [
    "Ishwarpur Municipality",
    "Malangwa Municipality",
    "Lalbandhi Municipality",
    "Haripur Municipality",
    "Haripurwa Municipality",
    "Hariwan Municipality",
    "Barahathawa Municipality",
    "Balara Municipality",
    "Godaita Municipality",
    "Bagmati Municipalty",
    "Kabilashi Municipality",
    "Chakaraghatta Rural Municipality",
    "Chandranagar Rural Municipality",
    "Dhankaul Rural Municipality",
    "Brahmapuri Rural Municipality",
    "Ramnagar Rural Municipality",
    "Bishnu Rural Municipality",
    "Basbariya Rural Municipality",
    "Kaudena Rural Municipality",
    "Parsa Rural Municipality"
  ],
  Sindhuli: [
    "Kamalamai Municipality",
    "Dudhauli Minicipality",
    "Golanjor Rural Municipality",
    "Ghyanglekh Rural Municipality",
    "Teenpatan Rural Municipality",
    "Fikkal Rural Municipality",
    "Maring Rural Municipality",
    "Sunkoshi Rural Municipality",
    "Hariharpurgadhi Rural Municipality",
  ],
  Sindhupalchok: [
    "Chautara-Sangachwok Gadhi Municipality",
    "Barahbise Municipality",
    "Melamchi Municipality",
    "Indrawati Rural Municipality",
    "Jugal Rural Municipality",
    "Panchpokhari-Thangpaal Rural Municipality",
    "Walefi Rural Municipality",
    "Bhotekoshi Rural Municipality",
    "Lisankhu Rural Municipality",
    "Sunkoshi Rural Municipality",
    "Helambu Rural Municipality",
    "Tripura Sundari Rural Municipality"
  ],
  Siraha: [
    "Lahan Municipality",
    "Dhangadhimai Municipality",
    "Siraha Municipality",
    "Golbajar Municipality",
    "Mirchaiya Municipality",
    "Kalyanpur Municipality",
    "Sukhipur Municipality",
    "Karjanha Municipality",
    "Bhagwanpur Rural Municipality",
    "Aurahi Rural Municipality",
    "Bishnupur Rural Municipality",
    "Bariyarpatti Rural Municipality",
    "Lakhsmipur Rural Municipality",
    "Naraha Rural Municipality",
    "Sakhuwanankarkatti Rural Municipality",
    "Arnama Rural Municipality",
    "Nawarajpur Rural Municipality",
  ],
  Solukhumbu: [
    "Solu-Dudhkunda Municipality",
    "Dudh Koshi Municipality",
    "Khumbu-Pasanglamu Rural Municipality",
    "Dudh Kausika Rural Municipality",
    "Necha Salyan Rural Municipality",
    "Mahakulung Rural Municipality",
    "Likhupike Rural Municipality",
    "Sotang Rural Municipality"
  ],
  Sunsari: [
    "Itahari Sub-Metropolitan City",
    "Dharan Sub-Metropolitan City",
    "Inaruwa Municipality",
    "Duhawi Municipality",
    "Ramdhuni Municipality",
    "Baraha Municipality",
    "Devgunj Rural Municipality",
    "Koshi Rural Municipality",
    "Gadhi Rural Municipality",
    "Barju Rural Municipality",
    "Bhokraha Rural Municipality",
    "Harinagara Rural Municipality"
  ],
  Surkhet: [
    "Barahatal Rural Municipality",
    "Bheriganga Municipality",
    "Birendranagar Municipality",
    "Chaukune Rural Municipality",
    "Chingad Rural Municipality",
    "Gurbha Kot Municipality",
    "Lekbesi Municipality",
    "Panchapuri Municipality",
    "Simta Rural Municipality"
  ],
  Syangja: [
    "Aandhikhola Rural Municipality",
    "Arjun Chaupari Rural Municipality",
    "Bheerkot Municipality",
    "Biruwa Rural Municipality",
    "Chapakot Municipality",
    "Galyang Municipality",
    "Harinas Rural Municipality",
    "Kaligandaki Rural Municipality",
    "Phedikhola Rural Municipality",
    "Putalibazar Municipality",
    "Waling Municipality"
  ],
  Tanahu: [
    "Anbu Khaireni Rural Municipality",
    "Bandipur Rural Municipality",
    "Bhanu Municipality",
    "Bhimad Municipality",
    "Byas Municipality",
    "Devghat Rural Municipality",
    "Ghiring Rural Municipality",
    "Myagde Rural Municipality",
    "Rhishing Rural Municipality",
    "Shuklagandaki Municipality"
  ],
  Taplejung: [
    "Fungling Municipality",
    "Aathrai-Triveni Rural Municipality",
    "Sidingwa Rural Municipality",
    "Faktalung Rural Municipality",
    "Mikwakhola Rural Municipality",
    "Meringden Rural Municipality",
    "Maiwakhola Rural Municipality",
    "Yangwarak Rural Municipality",
    "Siringa Rural Municipality"
  ],
  Tehrathum: [
    "Myanglung Municipality",
    "Laligurans Municipality",
    "Aathrai Rural Municipality",
    "Chathar Rural Municipality",
    "Fedam Rural Municipality",
    "Menchhayamem Rural Municipality",
  ],
  Udayapur: [
    "Katari Municipality",
    "Chaudandi Gadhi Municipality",
    "Triyuga Municipality",
    "Beliya Municipality",
    "Udayapurgadhi Rural Municipality",
    "Taapli Rural Municipality",
    "Rauta Mai Rural Municipality",
    "Sunkoshi Rural Municipality"
  ],
  WesternRukum: [
    "Aathbiskot Municipality",
    "Banphikot Rural Municipality",
    "Chaurjahari Municipality",
    "Musikot Municipality",
    "Sani Bheri Rural Municipality",
    "Tribeni Rural Municipality"
  ]
};

module.exports = localBodies;