const localBodies = {
  Achham: [],
  Arghakhanchi: [],
  Baglung: [],
  Baitadi: [],
  Bajhang: [],
  Bajura: [],
  Banke: [],
  Bara: [],
  Bardiya: [],
  Bhaktapur: [
    "Bhaktapur Municipality",
    "Changunarayan Municipality",
    "Madhyapur Thimi Municipality",
    "Suryabinayak Municipality"
  ],
  Bhojpur: [
    "Bhojpur Municipality",
    "Sadananda Municipality",
    "Tyamke-Maiyum Rural Municipality",
    "Ramprasad Rai Rural Municipality",
    "Arun Rural Municipality",
    "Pauwadhungma Rural Municipality",
    "Salpasillicho Rural Municipality",
    "Aamchwok Rural Municipality",
    "Hatuwagadhi Rural Municipality"
  ],
  Chitwan: [
    "Bharatpur Metropolitan City",
    "Ichchhakamana Rural Municipality",
    "Kalika Municipality",
    "Khairahani Municipality",
    "Madi Municipality",
    "Rapti Municipality",
    "Ratnanagar Municipality"
  ],
  Dadeldhura: [],
  Dailekh: [
    "Aathbis Municipality",
    "Bhagawatimai Rural Municipality",
    "Bhairabi Rural Municipality",
    "Chamunda Bindrasaini Municipality",
    "Dullu Municipality",
    "Dungeshwar Rural Municipality",
    "Gurans Rural Municipality",
    "Mahabu Rural Municipality",
    "Narayan Municipality",
    "Naumule Rural Municipality",
    "Thantikandh Rural Municipality"
  ],
  Dang: [],
  Darchula: [],
  Dhading: [],
  Dhankuta: [
    "Pakhribash Municipality",
    "Dhankuta Municipality",
    "Mahalakshmi Municipality",
    "Sangurigadhigadhi Rural Municipality",
    "Khalsha Chhintang Sahidbhumi Rural Municipality",
    "Chathar Jorpati Rural Municipality",
    "Chaubise Rural Municipality"
  ],
  Dhanusa: [],
  Dolakha: [
    "Baiteshwor Rural Municipality",
    "Bhimeswor Municipality",
    "Bigu Rural Municipality",
    "Gaurishankar Rural Municipality",
    "Jiri Municipality",
    "Kalinchok Rural Municipality",
    "Melung Rural Municipality",
    "Sailung Rural Municipality",
    "Tamakoshi Rural Municipality"
  ],
  Dolpa: [
    "Chharka Tangsong Rural Municipality",
    "Dolpo Buddha Rural Municipality",
    "Jagadulla Rural Municipality",
    "Kaike Rural Municipality",
    "Mudkechula Rural Municipality",
    "She Phoksundo Rural Municipality",
    "Thuli Bheri Municipality",
    "Tripurasundari Municipality"
  ],
  Doti: [],
  EasternRukum: [
    "Bhume Rural Municipality",
    "Putha Uttarganga Rural Municipality",
    "Sisne Rural Municipality"
  ],
  Gorkha: [],
  Gulmi: [],
  Humla: [
    "Adanchuli Rural Municipality",
    "Chankheli Rural Municipality",
    "Kharpunath Rural Municipality",
    "Namkha Rural Municipality",
    "Sarkegad Rural Municipality",
    "Simkot Rural Municipality",
    "Tajakot Rural Municipality"
  ],
  Ilam: [
    "Ilam Municipality",
    "Deumai Municipality",
    "Mai Municipality",
    "Suryodaya Municipality",
    "Fakfothum Rural Municipality",
    "Chulachuli Rural Municipality",
    "Mai Jogmai Rural Municipality",
    "Mangseung Rural Municipality",
    "Rong Rural Municipality",
    "Sandakpur Rural Municipality"
  ],
  Jajarkot: [
    "Barekot Rural Municipality",
    "Bheri Municipality",
    "Chhedagad Municipality",
    "Junichande Rural Municipality",
    "Kushe Rural Municipality",
    "Shivalaya Rural Municipality",
    "Tribeni Nalgad Municipality"
  ],
  Jhapa: [
    "Mechinagar Municipality",
    "Damak Municipality",
    "Kankai Municipality",
    "Bhadrapur Municipality",
    "Arjundhara Municipality",
    "Shivasatakshi Municipality",
    "Gauradaha Municipality",
    "Birtamod Municipality",
    "Kamal Rural Municipality",
    "Gaurigunj Rural Municipality",
    "Barhadashi Rural Municipality",
    "Jhapa Rural Municipality",
    "Buddhashanti Rural Municipality",
    "Hallibari Rural Municipality",
    "Kachankawal Rural Municipality"
  ],
  Jumla: [
    "Chandannath Municipality",
    "Guthichaur Rural Municipality",
    "Hima Rural Municipality",
    "Kankasundari Rural Municipality",
    "Patarasi Rural Municipality",
    "Sinja Rural Municipality",
    "Tatopani Rural Municipality",
    "Tila Rural Municipality"
  ],
  Kailali: [],
  Kalikot: [],
  Kanchanpur: [],
  Kapilvastu: [],
  Kaski: [],
  Kathmandu: [
    "Kathmandu Metropolitan City",
    "Kageshwori-Manohara Municipality",
    "Kirtipur Municipality",
    "Gokarneshwor Municipality",
    "Chandragiri Municipality",
    "Tokha Municipality",
    "Tarakeshwor Municipality",
    "Dakshinkali Municipality",
    "Nagarjun Municipality",
    "Budhanilkantha Municipality",
    "Shankhapur Municipality"
  ],
  Kavrepalanchowk: [],
  Khotang: [
    "Halesi-Tuwachung Municipality",
    "Rupakot-Majhuwagadhi Municipality",
    "Aishelukharka Rural Municipality",
    "Lamidanda Rural Municipality",
    "Jantedhunga Rural Municipality",
    "Khotehang Rural Municipality",
    "Kopilashgadhi Rural Municipality",
    "Diprung Rural Municipality",
    "Saakelaa Rural Municipality",
    "Brahapokhari Rural Municipality"
  ],
  Lalitpur: [],
  Lamjung: [],
  Mahottari: [],
  Makwanpur: [],
  Manang: [],
  Morang: [
    "Biratnagar Metropolitan City",
    "Belwari Municipality",
    "Letang Municipality",
    "Pathari-Sanishchare Municipality",
    "Rangeli Municipality",
    "Ratuwamai Municipality",
    "Sunwarsa Municipality",
    "Urlabari Municipality",
    "Sundar Haraicha Municipality",
    "Budiganga Rural Municipality",
    "Dhanpalthan Rural Municipality",
    "Gramthan Rural Municipality",
    "Jahada Rural Municipality",
    "Kanepohari Rural Municipality",
    "Katahari Rural Municipality",
    "Kerabari Rural Municipality",
    "Miklajung Rural Municipality"
  ],
  Mugu: [],
  Mustang: [],
  Myagdi: [],
  Nawalpur: [],
  Nuwakot: [],
  Okhaldhunga: [
    "Siddhicharan Municipality",
    "Khijidemba Rural Municipality",
    "Champadevi Rural Municipality",
    "Chisankhugadhi Rural Municipality",
    "Mane Bhanjyang Rural Municipality",
    "Molung Rural Municipality",
    "Likhu Rural Municipality",
    "Sunkoshi Rural Municipality"
  ],
  Palpa: [],
  Panchthar: [
    "Fidim Municipality",
    "Falelung Rural Municipality",
    "Falgunanda Rural Municipality",
    "Hilihang Rural Municipality",
    "Kummayak Rural Municipality",
    "Miklajung Rural Municipality",
    "Tumbewa Rural Municipality",
    "yangwarak Rural Municipality"
  ],
  Parasi: [],
  Parbat: [],
  Parsa: [],
  Pyuthan: [],
  Ramechhap: [],
  Rasuwa: [],
  Rautahat: [],
  Rolpa: [],
  Rupandehi: [],
  Salyan: [],
  Sankhuwasabha: [
    "Chainpur Municipality",
    "Dharmadevi Municipality",
    "Khadwari Municipality",
    "Maadi Municipality",
    "Panchkhapan Municipality",
    "Bhotkhola Rural Municipality",
    "Chichila Rural Municipality",
    "Makalu Rural Municipality",
    "Sabhaa Pokhari Rural Municipality",
    "Silichong Rural Municipality"
  ],
  Saptari: [],
  Sarlahi: [],
  Sindhuli: [],
  Sindhupalchok: [],
  Siraha: [],
  Solukhumbu: [
    "Solu-Dudhkunda Municipality",
    "Dudh Koshi Municipality",
    "Khumbu-Pasanglamu Rural Municipality",
    "Dudh Kausika Rural Municipality",
    "Necha Salyan Rural Municipality",
    "Mahakulung Rural Municipality",
    "Likhupike Rural Municipality",
    "Sotang Rural Municipality"
  ],
  Sunsari: [
    "Itahari Sub-Metropolitan City",
    "Dharan Sub-Metropolitan City",
    "Inaruwa Municipality",
    "Duhawi Municipality",
    "Ramdhuni Municipality",
    "Baraha Municipality",
    "Devgunj Rural Municipality",
    "Koshi Rural Municipality",
    "Gadhi Rural Municipality",
    "Barju Rural Municipality",
    "Bhokraha Rural Municipality",
    "Harinagara Rural Municipality"
  ],
  Surkhet: [
    "Barahatal Rural Municipality",
    "Bheriganga Municipality",
    "Birendranagar Municipality",
    "Chaukune Rural Municipality",
    "Chingad Rural Municipality",
    "Gurbha Kot Municipality",
    "Lekbesi Municipality",
    "Panchapuri Municipality",
    "Simta Rural Municipality"
  ],
  Syangja: [
    "Aandhikhola Rural Municipality",
    "Arjun Chaupari Rural Municipality",
    "Bheerkot Municipality",
    "Biruwa Rural Municipality",
    "Chapakot Municipality",
    "Galyang Municipality",
    "Harinas Rural Municipality",
    "Kaligandaki Rural Municipality",
    "Phedikhola Rural Municipality",
    "Putalibazar Municipality",
    "Waling Municipality"
  ],
  Tanahu: [],
  Taplejung: [
    "Fungling Municipality",
    "Aathrai-Triveni Rural Municipality",
    "Sidingwa Rural Municipality",
    "Faktalung Rural Municipality",
    "Mikwakhola Rural Municipality",
    "Meringden Rural Municipality",
    "Maiwakhola Rural Municipality",
    "Yangwarak Rural Municipality",
    "Siringa Rural Municipality"
  ],
  Tehrathum: [
    "Myanglung Municipality",
    "Laligurans Municipality",
    "Aathrai Rural Municipality",
    "Chathar Rural Municipality",
    "Fedam Rural Municipality",
    "Menchhayamem Rural Municipality"
  ],
  Udayapur: [
    "Katari Municipality",
    "Chaudandi Gadhi Municipality",
    "Triyuga Municipality",
    "Beliya Municipality",
    "Udayapurgadhi Rural Municipality",
    "Taapli Rural Municipality",
    "Rauta Mai Rural Municipality",
    "Sunkoshi Rural Municipality"
  ],
  WesternRukum: [
    "Aathbiskot Municipality",
    "Banphikot Rural Municipality",
    "Chaurjahari Municipality",
    "Musikot Municipality",
    "Sani Bheri Rural Municipality",
    "Tribeni Rural Municipality"
  ]
};

module.exports = localBodies;
