const localBodies = {
  Achham: [],
  Arghakhanchi: [],
  Baglung: [],
  Baitadi: [],
  Bajhang: [],
  Bajura: [],
  Banke: [],
  Bara: [],
  Bardiya: [],
  Bhaktapur: [
    "Bhaktapur Municipality",
    "Changunarayan Municipality",
    "Madhyapur Thimi Municipality",
    "Suryabinayak Municipality"
  ],
  Bhojpur: [],
  Chitwan: [
    "Bharatpur Metropolitan City",
    "Ichchhakamana Rural Municipality",
    "Kalika Municipality",
    "Khairahani Municipality",
    "Madi Municipality",
    "Rapti Municipality",
    "Ratnanagar Municipality"
  ],
  Dadeldhura: [],
  Dailekh: [],
  Dang: [],
  Darchula: [],
  Dhading: [],
  Dhankuta: [],
  Dhanusa: [],
  Dolakha: [
    "Baiteshwor Rural Municipality",
    "Bhimeswor Municipality",
    "Bigu Rural Municipality",
    "Gaurishankar Rural Municipality",
    "Jiri Municipality",
    "Kalinchok Rural Municipality",
    "Melung Rural Municipality",
    "Sailung Rural Municipality",
    "Tamakoshi Rural Municipality"
  ],
  Dolpa: [],
  Doti: [],
  EasternRukum: [
    "Bhume Rural Municipality",
    "Putha Uttarganga Rural Municipality",
    "Sisne Rural Municipality"
  ],
  Gorkha: [],
  Gulmi: [],
  Humla: [],
  Ilam: [
    "Ilam Municipality",
    "Deumai Municipality",
    "Mai Municipality",
    "Suryodaya Municipality",
    "Fakfothum Rural Municipality",
    "Chulachuli Rural Municipality",
    "Mai Jogmai Rural Municipality",
    "Mangseung Rural Municipality",
    "Rong Rural Municipality",
    "Sandakpur Rural Municipality"
  ],
  Jajarkot: [],
  Jhapa: [],
  Jumla: [],
  Kailali: [],
  Kalikot: [],
  Kanchanpur: [],
  Kapilvastu: [],
  Kaski: [],
  Kathmandu: [
    "Kathmandu Metropolitan City",
    "Kageshwori-Manohara Municipality",
    "Kirtipur Municipality",
    "Gokarneshwor Municipality",
    "Chandragiri Municipality",
    "Tokha Municipality",
    "Tarakeshwor Municipality",
    "Dakshinkali Municipality",
    "Nagarjun Municipality",
    "Budhanilkantha Municipality",
    "Shankhapur Municipality"
  ],
  Kavrepalanchowk: [],
  Khotang: [],
  Lalitpur: [],
  Lamjung: [],
  Mahottari: [],
  Makwanpur: [],
  Manang: [],
  Morang: [],
  Mugu: [],
  Mustang: [],
  Myagdi: [],
  Nawalpur: [],
  Nuwakot: [],
  Okhaldhunga: [],
  Palpa: [],
  Panchthar: [
    "Fidim Municipality",
    "Falelung Rural Municipality",
    "Falgunanda Rural Municipality",
    "Hilihang Rural Municipality",
    "Kummayak Rural Municipality",
    "Miklajung Rural Municipality",
    "Tumbewa Rural Municipality",
    "yangwarak Rural Municipality"
  ],
  Parasi: [],
  Parbat: [],
  Parsa: [],
  Pyuthan: [],
  Ramechhap: [],
  Rasuwa: [],
  Rautahat: [],
  Rolpa: [],
  Rupandehi: [],
  Salyan: [],
  Sankhuwasabha: [],
  Saptari: [],
  Sarlahi: [],
  Sindhuli: [],
  Sindhupalchok: [],
  Siraha: [],
  Solukhumbu: [],
  Sunsari: [],
  Surkhet: [
    "Barahatal Rural Municipality",
    "Bheriganga Municipality",
    "Birendranagar Municipality",
    "Chaukune Rural Municipality",
    "Chingad Rural Municipality",
    "Gurbha Kot Municipality",
    "Lekbesi Municipality",
    "Panchapuri Municipality",
    "Simta Rural Municipality"
  ],
  Syangja: [
    "Aandhikhola Rural Municipality",
    "Arjun Chaupari Rural Municipality",
    "Bheerkot Municipality",
    "Biruwa Rural Municipality",
    "Chapakot Municipality",
    "Galyang Municipality",
    "Harinas Rural Municipality",
    "Kaligandaki Rural Municipality",
    "Phedikhola Rural Municipality",
    "Putalibazar Municipality",
    "Waling Municipality"
  ],
  Tanahu: [],
  Taplejung: [
    "Fungling Municipality",
    "Aathrai-Triveni Rural Municipality",
    "Sidingwa Rural Municipality",
    "Faktalung Rural Municipality",
    "Mikwakhola Rural Municipality",
    "Meringden Rural Municipality",
    "Maiwakhola Rural Municipality",
    "Yangwarak Rural Municipality",
    "Siringa Rural Municipality"
  ],
  Tehrathum: [],
  Udayapur: [],
  WesternRukum: [
    "Aathbiskot Municipality",
    "Banphikot Rural Municipality",
    "Chaurjahari Municipality",
    "Musikot Municipality",
    "Sani Bheri Rural Municipality",
    "Tribeni Rural Municipality"
  ]
};

module.exports = localBodies;
